# Generated by Django 5.0.6 on 2024-07-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
